export const SET_AUTH_CHECKED: 'SET_AUTH_CHECKED' = 'SET_AUTH_CHECKED'
export const SET_USER: 'SET_USER' = 'SET_USER'

export const ADD_INGREDIENT: 'ADD_INGREDIENT' = 'ADD_INGREDIENT'
export const DELETE_INGREDIENT: 'DELETE_INGREDIENT' = 'DELETE_INGREDIENT'
export const CLEAR_INGREDIENTS: 'CLEAR_INGREDIENTS' = 'CLEAR_INGREDIENTS'
export const ADD_BUN: 'ADD_BUN' = 'ADD_BUN'
export const CONSTRUCTOR_REORDER: 'CONSTRUCTOR_REORDER' = 'CONSTRUCTOR_REORDER'

export const SET_CURRENT_INGREDIENT: 'SET_CURRENT_INGREDIENT' = 'SET_CURRENT_INGREDIENT'
export const REMOVE_CURRENT_INGREDIENT: 'REMOVE_CURRENT_INGREDIENT' = 'REMOVE_CURRENT_INGREDIENT'

export const PASSWORD_FORGOT_SET_EMAIL: 'PASSWORD_FORGOT_SET_EMAIL' = 'PASSWORD_FORGOT_SET_EMAIL'
export const PASSWORD_FORGOT_SUBMIT: 'PASSWORD_FORGOT_SUBMIT' = 'PASSWORD_FORGOT_SUBMIT'
export const PASSWORD_FORGOT_SUBMIT_SUCCESS: 'PASSWORD_FORGOT_SUBMIT_SUCCESS' = 'PASSWORD_FORGOT_SUBMIT_SUCCESS'
export const PASSWORD_FORGOT_SUBMIT_FAILED: 'PASSWORD_FORGOT_SUBMIT_FAILED' = 'PASSWORD_FORGOT_SUBMIT_FAILED'

export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST'
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS'
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED'

export const LOGIN_FORM_SET_VALUE: 'LOGIN_FORM_SET_VALUE' = 'LOGIN_FORM_SET_VALUE'
export const LOGIN_FORM_SUBMIT: 'LOGIN_FORM_SUBMIT' = 'LOGIN_FORM_SUBMIT'
export const LOGIN_FORM_SUBMIT_SUCCESS: 'LOGIN_FORM_SUBMIT_SUCCESS' = 'LOGIN_FORM_SUBMIT_SUCCESS'
export const LOGIN_FORM_SUBMIT_FAILED: 'LOGIN_FORM_SUBMIT_FAILED' = 'LOGIN_FORM_SUBMIT_FAILED'

export const SET_INGREDIENTS: 'SET_INGREDIENTS' = 'SET_INGREDIENTS'
export const CLOSE_ORDER: 'CLOSE_ORDER' = 'CLOSE_ORDER'
export const ORDER_POST_REQUEST: 'ORDER_POST_REQUEST' = 'ORDER_POST_REQUEST'
export const ORDER_POST_SUCCESS: 'ORDER_POST_SUCCESS' = 'ORDER_POST_SUCCESS'
export const ORDER_POST_FAILED: 'ORDER_POST_FAILED' = 'ORDER_POST_FAILED'

export const PROFILE_FORM_SET_VALUE: 'PROFILE_FORM_SET_VALUE' = 'PROFILE_FORM_SET_VALUE'
export const PROFILE_FORM_SUBMIT: 'PROFILE_FORM_SUBMIT' = 'PROFILE_FORM_SUBMIT'
export const PROFILE_FORM_SUBMIT_SUCCESS: 'PROFILE_FORM_SUBMIT_SUCCESS' = 'PROFILE_FORM_SUBMIT_SUCCESS'
export const PROFILE_FORM_SUBMIT_FAILED: 'PROFILE_FORM_SUBMIT_FAILED' = 'PROFILE_FORM_SUBMIT_FAILED'
export const PROFILE_LOGOUT_SUCCESS: 'PROFILE_LOGOUT_SUCCESS' = 'PROFILE_LOGOUT_SUCCESS'
export const PROFILE_LOGOUT_FAILED: 'PROFILE_LOGOUT_FAILED' = 'PROFILE_LOGOUT_FAILED'

export const REGISTER_FORM_SET_VALUE: 'REGISTER_FORM_SET_VALUE' = 'REGISTER_FORM_SET_VALUE'
export const REGISTER_FORM_SUBMIT: 'REGISTER_FORM_SUBMIT' = 'REGISTER_FORM_SUBMIT'
export const REGISTER_FORM_SUBMIT_SUCCESS: 'REGISTER_FORM_SUBMIT_SUCCESS' = 'REGISTER_FORM_SUBMIT_SUCCESS'
export const REGISTER_FORM_SUBMIT_FAILED: 'REGISTER_FORM_SUBMIT_FAILED' = 'REGISTER_FORM_SUBMIT_FAILED'

export const PASSWORD_RESET_SET_VALUE: 'PASSWORD_FORGOT_SET_EMAIL' = 'PASSWORD_FORGOT_SET_EMAIL'
export const PASSWORD_RESET_SUBMIT: 'PASSWORD_FORGOT_SUBMIT' = 'PASSWORD_FORGOT_SUBMIT'
export const PASSWORD_RESET_SUBMIT_SUCCESS: 'PASSWORD_FORGOT_SUBMIT_SUCCESS' = 'PASSWORD_FORGOT_SUBMIT_SUCCESS'
export const PASSWORD_RESET_SUBMIT_FAILED: 'PASSWORD_FORGOT_SUBMIT_FAILED' = 'PASSWORD_FORGOT_SUBMIT_FAILED'

export const GET_ORDER_REQUEST: 'GET_ORDER_REQUEST' = 'GET_ORDER_REQUEST'
export const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS'
export const GET_ORDER_FAILED: 'GET_ORDER_FAILED' = 'GET_ORDER_FAILED'

export enum WebsocketStatus {
    CONNECTING = 'CONNECTINg',
    ONLINE = 'ONLINE',
    OFFLINE = 'OFFLINE'
}